//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by geticgui.rc
//
#define IDR_MAINFRAME                   99
#define IDD_ABOUTBOX                    100
#define IDI_ICON8                       101
#define BMP_SCENE                       101
#define IDR_SCE_ITEM1                   101
#define IDI_ICON1                       102
#define DLG_CONSOLE                     103
#define ICO_COLAPSED                    103
#define IDR_GSCRIPT_ENGINE              104
#define IDD_DIALOG2                     104
#define DLG_ITEMSETT                    105
#define DLG_CUSTITEM                    105
#define DLG_EDITOR2D                    106
#define IDB_BITMAP                      106
#define IDR_ZEDMAP                      109
#define IDR_IGETIC                      110
#define IDR_TOOLBAR1                    111
#define IDR_GETICPLUG                   112
#define IDR_GETICEDITOR                 113
#define IDR_MENU1                       114
#define BMP_PAT                         115
#define IDC_CROTATE                     116
#define IDR_3DEDITACCEL                 117
#define TB_BUILD                        118
#define IDR_Z_ED2TYPE                   119
#define IDC_SCROLL                      131
#define IDC_CSCALE                      133
#define DLG_TEX                         134
#define IDC_CURSOR3                     135
#define IDC_CMOVE                       136
#define IDB_ABOUTMAR                    139
#define DLG_NEWBRUSH                    143
#define DLG_GS                          144
#define IDB_ABOUTBOX                    146
#define TB_ALIGN                        150
#define TB_QUADRAICS                    151
#define DLG_WAIT                        152
#define TB_MAKE                         152
#define TB_CSG                          153
#define TB_SELECT                       154
#define BMP_DEF                         155
#define DLG_COMPILERPROG                155
#define DLG_F_SET                       156
#define TB_VIEWS                        156
#define DLG_B_SET                       157
#define TB_MOVE                         157
#define DLG_COMPILESET                  158
#define IDR_SINTACTICEF                 158
#define IDC_CURSOR1                     159
#define DLG_ITEMS                       159
#define DLG_SCRIPT                      160
#define BMP_LIGHTBULB                   161
#define DLG_SOUNDS                      161
#define DLG_SKYDOM                      163
#define DLG_SCENE                       164
#define DLG_I_LIGHT                     165
#define DLG_NEWITEM                     166
#define DLG_CMODELSAVE                  169
#define DLG_NEWPREF                     170
#define DLG_MOTIONSTATE                 174
#define TB_MAIN256                      175
#define DLG_I_TRIGER                    175
#define TB_MAIN257                      176
#define DLG_I_WEAPON                    176
#define BMP_ST                          177
#define BMP_SCT                         178
#define ICO_SCT                         179
#define DLG_WPNCFG                      180
#define ICO_SCT1                        180
#define DL_EDXYZ                        189
#define DL_UV                           190
#define DL_COLOR                        191
#define DL_FILEPCK                      192
#define DL_CHECKS                       194
#define DL_EDSPIN                       195
#define DL_CBSEL                        196
#define DL_RANGE                        197
#define DL_RGB                          198
#define DL_EDIT                         199
#define DLG_SPLASH                      200
#define SPLASH_BMP                      201
#define DLG_TEXREF                      203
#define DLG_LEV_EXPLORE                 204
#define SPLASH_EDIT                     207
#define IDR_GSCRIPT_HDR1                209
#define IDR_PLUGIN_HDR                  210
#define IDD_DIALOG_CPP                  213
#define DLG_COMPILERSETT                215
#define TB_ALIGN_24E                    216
#define TB_BUILD_24E                    217
#define TB_CSG_24E                      218
#define TB_MAKE_24E                     219
#define TB_MOVE_24E                     220
#define TB_QUADRAICS_24E                221
#define TB_SELECT_24E                   222
#define TB_VIEWS_24E                    223
#define TB_ALIGN_24D                    224
#define TB_BUILD_24D                    225
#define TB_CSG_24D                      226
#define TB_MAKE_24D                     227
#define TB_MOVE_24D                     228
#define TB_QUADRAICS_24D                229
#define TB_SELECT_24D                   230
#define TB_VIEWS_24D                    231
#define TB_ALIGN_24R                    232
#define TB_BUILD_24R                    233
#define TB_CSG_24R                      234
#define TB_MAKE_24R                     235
#define TB_MOVE_24R                     236
#define TB_QUADRAICS_24R                237
#define TB_SELECT_24R                   238
#define TB_VIEWS_24R                    239
#define IDD_DIALOG1                     302
#define DLG_PREFS                       303
#define DLG_TEX_MODY                    304
#define BMP_2D_TEX                      308
#define CUR_HANDO                       315
#define CUR_HANDC                       316
#define DLG_AUTODETAILS                 317
#define ICO_ANI_1                       318
#define ICO_ANI_2                       319
#define ICO_ANI_3                       320
#define ICO_ANI_4                       321
#define IDI_GET                         322
#define ICO_EXPANDED                    323
#define IDB_ITEM_TYPES                  324
#define TB_SLINETTIP                    325
#define IDB_BITMAP1                     326
#define IDC_STATICF                     1000
#define IDC_TAB1                        1000
#define PB_LOGO                         1000
#define IDC_BUTTON1                     1001
#define IDC_STATICF2                    1001
#define TR_SCENE                        1001
#define SL_SPLASH                       1001
#define PC_CLOSE                        1002
#define PB_TFIRE                        1002
#define IDC_STATICF3                    1002
#define LB_EVENTS                       1002
#define IDC_BUTTON4                     1002
#define PB_SELECTED                     1002
#define CK_ALPHA                        1002
#define PB_DELLOGO                      1002
#define PB_TBLOB                        1003
#define PB_OK                           1003
#define PB_SELBOX                       1003
#define ST                              1003
#define ST_TEXTUREFLD                   1003
#define IDC_BUTTON6                     1003
#define PB_TPLASMA                      1004
#define PB_CSTART                       1004
#define EF_DETAILS                      1004
#define TREE_BSP                        1004
#define IDC_BUTTON7                     1004
#define PB_TWATER                       1005
#define IDC_CHECK1                      1005
#define PB_BACKGR                       1005
#define PB_TLAVA                        1006
#define CK_BACKFACE                     1006
#define IDC_CHECK2                      1006
#define PB_PROJBRSH                     1006
#define CK_QUADRATIC                    1006
#define PB_TSCRIPT                      1007
#define CK_LIGHT                        1007
#define IDC_CHECK3                      1007
#define PB_PORTALS1                     1007
#define IDC_CHECK13                     1008
#define ST_NAME                         1008
#define PB_PORTALS2                     1008
#define CK_CULLTERR                     1008
#define IDC_CHECK8                      1009
#define ST_SIZE                         1009
#define PB_DETAIL                       1009
#define CK_NOTILE                       1009
#define CK_KEEPPRJ_TEX                  1009
#define IDC_CHECK10                     1010
#define ST_BPP                          1010
#define PB_TERRAIN                      1010
#define ST_TFN0                         1010
#define CK_NOTILE1                      1010
#define PB_HOMEDIR                      1010
#define IDC_CHECK14                     1011
#define PB_TRIGGERBRSH                  1011
#define ST_TFN1                         1011
#define CK_DISGRPCSG                    1011
#define CK_NOTILE2                      1011
#define IDC_LIST1                       1012
#define IDC_CHECK15                     1012
#define ST_TFN2                         1012
#define CK_NOTILE3                      1012
#define IDC_CHECK16                     1013
#define IDC_SNDLIST                     1013
#define IDC_LISTASSOC                   1013
#define PB_MOTION                       1013
#define ST_TFN3                         1013
#define CK_NOTILE4                      1013
#define IDC_LIST3                       1013
#define RB_CM                           1014
#define IDC_CHECK17                     1014
#define PB_TRIGGER                      1014
#define CK_GOR                          1014
#define IDC_STATICL                     1014
#define EF_NOTE                         1014
#define RB_M                            1015
#define IDC_CHECK18                     1015
#define CK_FULLBR                       1015
#define RB_FEET                         1016
#define IDC_CHECK19                     1016
#define CK_NOLM                         1016
#define IDC_CHECK20                     1017
#define RB_TSHIFT                       1017
#define IDC_EDIT2                       1018
#define IDC_CHECK21                     1018
#define CK_NOCOLLIDE                    1018
#define CK_SHOWTP                       1018
#define IDC_SPIN1                       1019
#define EF_INTENSITY                    1019
#define IDC_CHECK22                     1019
#define RB_TVIBR                        1019
#define PB_SELECT                       1019
#define PB_UNLOCK                       1019
#define IDC_COMBO1                      1020
#define IDC_EDIT3                       1020
#define CB_CONTENT                      1020
#define SP_MINDIM                       1020
#define IDC_CHECK23                     1020
#define CK_SHOWCB                       1020
#define ST_VIEW                         1020
#define ST_QUAKE                        1020
#define IDC_SPIN2                       1021
#define SP_MAXDIM                       1021
#define EF_SDX                          1021
#define IDC_CHECK24                     1021
#define TR_DIRS                         1021
#define PB_IMPORT                       1021
#define SP_MINPOLYS                     1022
#define EF_SDY                          1022
#define IDC_EDIT4                       1022
#define EF_MAXHALLORADIUS               1023
#define IDC_SPIN3                       1023
#define IDC_CHECK26                     1023
#define SP_CAMFAR                       1023
#define CK_SHOWLC                       1023
#define EF_SDZ                          1024
#define IDC_EDIT5                       1024
#define IDC_CHECK27                     1024
#define LB_COPRP                        1024
#define EF_HEIGHT                       1025
#define IDC_SPIN4                       1025
#define IDC_EDIT10                      1025
#define EF_MAXDIST                      1025
#define CK_SHOWLC2                      1025
#define CK_SHOW_FRUSTCULL               1025
#define RB_LIN                          1025
#define EF_DEPTH                        1026
#define IDC_CHECK28                     1026
#define RB_SPH                          1026
#define IDC_CHECK29                     1027
#define CB_EFFECTS                      1027
#define RB_LIN3                         1027
#define RB_CYL                          1027
#define IDC_CHECK30                     1028
#define IDC_CHECK31                     1029
#define CB_AMBIENT                      1029
#define EF_SOUND                        1030
#define CK_BRUSH                        1032
#define CK_ROTATION                     1032
#define CK_GENSC                        1032
#define CK_SCRIPT                       1033
#define CK_TANIM                        1033
#define CK_GENSC2                       1033
#define CK_GENSS                        1034
#define CK_GENSS2                       1035
#define CK_SHELL                        1037
#define IDC_EDIT1                       1038
#define EF_YR                           1039
#define EF_MINDIM                       1039
#define EF_X                            1039
#define IDC_EDIT6                       1039
#define EF_ZR                           1040
#define EF_Z                            1040
#define RB_SOLID                        1040
#define EF_CAMFAR                       1040
#define EF_R                            1041
#define RB_CUT                          1041
#define EF_USPEED                       1041
#define EF_A                            1042
#define RB_CUTALL                       1042
#define EF_VSPEED                       1042
#define EF_RX                           1042
#define EF_MAXDIM                       1043
#define EF_TIME                         1043
#define EF_RY                           1043
#define EF_MINPOLYS                     1044
#define EF_TIME2                        1044
#define EF_RZ                           1044
#define CK_SETDETAIL                    1045
#define EF_TEAM                         1045
#define CK_REVERSE                      1046
#define IDC_STATICT                     1047
#define IDC_STATICRS                    1048
#define IDC_STATICVS                    1049
#define CK_FLATERN                      1050
#define CK_DETACHED                     1050
#define TAB_DLGS                        1055
#define EF_OUT                          1058
#define IDC_BUTTON2                     1059
#define PB_ROTATE                       1059
#define PB_DEL                          1060
#define IDC_BUTTON5                     1060
#define PB_COLOR                        1061
#define PB_FLIPH                        1061
#define EF_ALPHA                        1062
#define PB_FLIPV                        1062
#define EF_CONST                        1063
#define EF_NORM                         1064
#define PB_REUV                         1065
#define PB_DIFUZE                       1066
#define EF_BRUSHNAME                    1066
#define EF_SPEEDU                       1067
#define EF_SPEEDV                       1068
#define EF_SLICESX                      1069
#define EF_AREA                         1069
#define CK_SHOWCUTS                     1070
#define IDC_CHECK4                      1070
#define PB_EMMISIVE                     1070
#define CK_BYAREA                       1070
#define EF_MATNAME                      1070
#define CB_GROUP                        1071
#define EF_SLICESY                      1071
#define CB_BULTYPO                      1071
#define IDC_BUTTON3                     1072
#define EF_VOL                          1072
#define EF_USERVALS                     1072
#define PB_EDIT                         1073
#define RB_LINEAR                       1073
#define EF_BUMP                         1073
#define RB_CYLINDRIC                    1074
#define PB_SPEC                         1074
#define RB_SPHERIC                      1075
#define EF_STICK                        1075
#define EF_TEXFLAG                      1076
#define RB_ENVI                         1076
#define PB_RESETSPLITS                  1076
#define IDC_STATIC1                     1077
#define EF_LAYER                        1077
#define IDC_STATIC2                     1078
#define IDC_STATIC3                     1079
#define ST_SKIDOM                       1079
#define CK_CUT                          1080
#define CK_CUTALL                       1081
#define CK_DETAIL                       1082
#define CK_NOCOLL                       1083
#define CK_DYNAMIC                      1084
#define CK_TRIANGS                      1085
#define CK_NOBSP                        1086
#define IDC_STATIC4                     1087
#define ST_DETAIL                       1087
#define IDC_STATICTA                    1088
#define CK_SPHBB                        1088
#define PB_CANCEL                       1089
#define IDC_STATICTA2                   1089
#define CK_CYLBB                        1089
#define IDC_STATICTA3                   1090
#define PB_EXPAND                       1090
#define CK_TERRVIS                      1090
#define PB_CLEAR                        1091
#define IDC_STATICTA4                   1091
#define ST_BIGTERR                      1091
#define IDC_STATICTA5                   1092
#define IDC_STATICA                     1098
#define IDC_LIST2                       1099
#define PB_SELTBT                       1100
#define IDC_LIST4                       1100
#define IDC_STATICMAT                   1101
#define IDC_LIST5                       1101
#define CK_INGNORE                      1102
#define IDC_LIST6                       1102
#define LB_SCPROPS                      1108
#define EF_RADIUS                       1110
#define CK_SPOT                         1111
#define EF_SPOTANGLE                    1112
#define EF_MINHALLORADIUS               1113
#define CK_COLLIDE                      1113
#define PB_ADD                          1114
#define EF_MINDIST                      1114
#define CK_AMBIENT                      1114
#define PB_ADDSND                       1115
#define IDC_STATICD                     1116
#define IDC_STATICMR                    1117
#define CK_REPEAT                       1117
#define IDC_STATICR                     1118
#define IDC_STATICMR2                   1119
#define ST_PLACEDLG                     1120
#define IDC_STATICR2                    1120
#define IDC_STATICGL                    1121
#define LB_PREFS                        1122
#define EF_WIDTH                        1123
#define LB_ITEMS                        1128
#define CK_DLIGHT                       1133
#define ST_DLGTEX                       1134
#define ST_GL                           1135
#define CK_CLOUDS                       1136
#define CK_LAVA                         1137
#define CK_WATER                        1138
#define EF_Y                            1139
#define CK_SKYDOM                       1140
#define EF_E                            1140
#define ST_STEPS                        1148
#define EF_STEPS                        1149
#define CK_LOOP                         1151
#define ST_MSG                          1152
#define CK_CKSCRIPT                     1152
#define CB_WPNTYPE                      1158
#define CK_MESH                         1159
#define CK_MESH2                        1160
#define CK_MESH3                        1161
#define ST_MESHBULL                     1162
#define ST_MESHWPN                      1163
#define EF_AMMOCNT                      1164
#define CB_TYPE                         1165
#define EF_AMMOCNT4                     1169
#define CK_DETBRSH                      1171
#define IDC_STATICB2                    1175
#define IDC_STATICB                     1176
#define CK_ROTATE                       1177
#define EF_XR                           1178
#define EF_NAME                         1179
#define EF_XC                           1180
#define EF_SCRIPT                       1180
#define EF_YC                           1181
#define CK_TEXTURE                      1181
#define EF_ZC                           1182
#define LB_TEX                          1182
#define EF_CATNAME                      1182
#define EF_W                            1183
#define EF_FILTER                       1183
#define EF_H                            1184
#define EF_D                            1185
#define LB_CO                           1185
#define RB_SHIFT                        1186
#define T3_X                            1186
#define RB_SPIN                         1187
#define T3_Z                            1187
#define RB_RADIAL                       1188
#define TA_STAGE                        1188
#define RB_WAVY                         1189
#define RB_WINDY                        1190
#define RB_FRAMING                      1191
#define RB_TGRANDOM                     1192
#define RB_TGFIRE                       1193
#define RB_TGBLOBS                      1194
#define RB_TGPLASMA                     1195
#define RB_TGWATER                      1196
#define RB_TGLAVA                       1197
#define CK_MIRROR                       1201
#define CK_SKY                          1202
#define CK_RANDOM                       1213
#define RB_PULSEI                       1214
#define CK_L0                           1214
#define RB_RANDOMI                      1215
#define CK_L1                           1215
#define RB_SCRIPTI                      1216
#define CK_L2                           1216
#define RB_VAWYI                        1217
#define CK_L3                           1217
#define RB_FLASHYI                      1218
#define RB_NORMALI                      1219
#define IDC_TREE1                       1220
#define TR_BROWSE                       1221
#define PB_TRAND                        1222
#define ST_GROUP                        1224
#define EF_POSX                         1225
#define LB_DETBRUSHES                   1226
#define EF_POSY                         1226
#define LB_SOUNDS                       1227
#define EF_POSZ                         1227
#define EF_DX                           1228
#define LC_TEXREFS                      1230
#define ST_BMPSSZ                       1231
#define CK_TRIGGED                      1232
#define PB_REFRESH                      1233
#define CK_SINGLETON                    1233
#define CK_SOUND                        1236
#define PB_NEW                          1237
#define PB_COMPILE                      1239
#define LB_OUT                          1242
#define PB_SELPATH                      1243
#define EF_SEED                         1245
#define PB_GENTERIAN                    1246
#define SP_Y                            1247
#define SP_X                            1248
#define CK_TERRAIN                      1249
#define SP_H                            1249
#define EF_MINR                         1250
#define EF_MAXR                         1251
#define EF_COUNT                        1252
#define CK_NOCOLIDE                     1263
#define CK_NOLIGHT                      1264
#define CK_OCCLUDER                     1264
#define CK_FULLBRIGHT                   1265
#define CK_HALLO                        1266
#define CK_SHOWBACK                     1267
#define CK_HALLO2                       1267
#define CK_METALIC                      1268
#define CK_FOGGY                        1269
#define CK_CUSTLM                       1269
#define CK_BLACK_MSK                    1270
#define CK_TEXANIM                      1271
#define CK_LPATCH                       1272
#define CK_GSHADE                       1273
#define EF_CONSOLE                      1274
#define CK_NOPROJ                       1274
#define PB_RUN                          1275
#define EF_RESPONSE                     1276
#define ST_PLACE                        1278
#define PAGE_1                          1279
#define PAGE_2                          1280
#define PB_P2                           1281
#define PB_P1                           1282
#define PB_P32                          1283
#define PB_P3                           1284
#define EF_RAD                          1284
#define PB_PLAY                         1285
#define PB_SCRIPT                       1286
#define LB_PROPS                        1287
#define LB_ITEMCAT                      1288
#define EF_RANGE                        1290
#define EF_AI                           1291
#define CK_FORCE                        1292
#define CK_CARVE                        1293
#define CK_SPLITTER                     1294
#define CK_ZONE                         1295
#define PB_12                           1296
#define PM_21                           1297
#define EF_FILEEXE                      1299
#define PB_BROWSE                       1300
#define ST_CATNAME                      1301
#define LB_PROPSCAT                     1302
#define ST_PLACE_DLG                    1303
#define IDC_CUSTOM1                     1305
#define IDC_SCROLLBAR1                  1306
#define ST_SPLASH                       1307
#define IDC_STATICF1                    1310
#define IDC_STATICF23                   1311
#define IDC_STATICF32                   1312
#define IDC_STATICO1                    1313
#define IDC_STATICO2                    1314
#define CK_SPLINE                       1315
#define IDC_STATICF24                   1315
#define PB_PREV                         1317
#define ST_CUR                          1318
#define PB_NEXT                         1319
#define PB_MAKE                         1320
#define PB_DELTEX                       1320
#define RB_RECT                         1321
#define RB_SPLINE                       1322
#define EF_CPCTS                        1323
#define EF_STPCTS                       1324
#define CK_DISABLE                      1324
#define GL_STATIC                       1325
#define RB_NURB                         1325
#define PB_CUT                          1326
#define RB_11                           1327
#define RB_22                           1328
#define CK_BW                           1328
#define RB_33                           1329
#define CK_BW2                          1329
#define IDC_RADIO1                      1330
#define IDC_RADIO2                      1331
#define IDC_RADIO3                      1332
#define IDC_RADIO4                      1333
#define CK_MASK                         1334
#define IDC_RADIO5                      1334
#define SL_MIN                          1335
#define CK_NEGATIVE                     1336
#define SL_CONTRAST                     1337
#define SL_LUMIN                        1338
#define SL_GAMMA                        1339
#define SL_INTENS                       1340
#define PB_RELOAD                       1341
#define IDC_COMBO2                      1343
#define CB_TEXTURE_MODE                 1343
#define CB_TK                           1343
#define CB_TTARGET                      1343
#define IDC_COMBO3                      1344
#define CB_TF                           1344
#define IDC_CHECK5                      1345
#define CB_TGEN                         1345
#define CB_LAYOUT                       1345
#define CB_TEXSTAGE                     1346
#define C_GENTEXCOORD                   1347
#define RB_RS                           1348
#define RB_CBST                         1348
#define RB_RST                          1349
#define RB_CBRST                        1349
#define RB_SPHST                        1350
#define CK_CLAMP                        1354
#define ST_EXPL                         1355
#define IDC_3                           1356
#define CK_3DIMM                        1357
#define PAGE                            1358
#define EF_STEPSS                       1359
#define PAGE2                           1359
#define GROUP1                          1360
#define PAGE3                           1360
#define GROUP2                          1361
#define GROUP3                          1362
#define CK_T0                           1363
#define CK_T1                           1364
#define CK_T2                           1365
#define CK_T3                           1366
#define ST_USER_U                       1368
#define IDC_SLIDER1                     1371
#define PB_CHECK                        1372
#define ST_ANI_ICON                     1373
#define GROUPS0                         1374
#define GROUPS1                         1375
#define ST_OUT                          1376
#define ST_RUNS                         1377
#define CK_CSGDETS                      1379
#define RB_FACES                        1380
#define RB_BRUSHES                      1381
#define CK_BYPOLIS                      1382
#define CK_AUTOBACKUP                   1383
#define EF_VER                          1384
#define ST_VER                          1385
#define ST_BUYG                         1386
#define ST_SZ                           1387
#define ST_TEXFRM                       1388
#define FRM_TEXMAP                      1389
#define FRM_MATPRP                      1390
#define FRM_MATPRP2                     1391
#define FRM_MATPRP3                     1392
#define ST_GLCTL                        1395
#define ST_T0                           1396
#define ST_L0                           1396
#define ST_T1                           1397
#define ST_0                            1397
#define ST_L1                           1397
#define ST_T2                           1398
#define ST_1                            1398
#define ST_L3                           1398
#define CK_ANIM                         1398
#define ST_L2                           1399
#define IDC_PROGRESS1                   1400
#define IDOK3                           1401
#define CK_USE_SPLITER                  1402
#define ST_LIDXSP                       1403
#define CK_SELBR                        1404
#define CK_BLACKMASK                    1404
#define CK_TASK                         1405
#define CK_CALCNORMALS                  1406
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define DLG_NEWTERIAN                   8603
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDR_MAINFRAMEMDS                8604
#define IDC_EDIT_TEXT                   8605
#define DLG_SCRIPT_BAR                  8605
#define DLG_I_AMMO                      8606
#define IDC_EDIT_REPLACE                8607
#define DLG_I_CUSTOM                    8607
#define IDC_EDIT_REPLACE_ALL            8608
#define TAB_AMMO                        8608
#define IDC_EDIT_REPLACE_WITH           8609
#define TAB_ACTOR                       8609
#define IDC_EDIT_SKIP                   8610
#define TAB_EXPLOSION                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define TAB_SMOKES                      8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define TAB_WEAPON                      8617
#define DLG_CLASS_ITEM                  8618
#define DLG_I_ACTOR                     8619
#define DLG_I_GAMEITEM                  8620
#define DLG_NEWGAMEITEM                 8621
#define DLG_I_GAMEITM                   8622
#define DL_RGB1                         8623
#define DLG_MATERIALS                   8624
#define DLG_B_SET1                      8625
#define DLG_NEWMATERIAL                 8625
#define DLG_F_SET1                      8626
#define DLG_TEXBROWSER                  8626
#define EF_SHINE                        8627
#define DLG_I_SOUND                     8627
#define DLG_I_STARTPLAY                 8628
#define DLG_LEAFS                       8629
#define DLG_CONSOLE1                    8630
#define DLG_ASSOC                       8630
#define DLG_COMPILERPROG1               8631
#define ID_TB_LOCKXYZ                   22771
#define ID_BUROTATE                     22773
#define ID_BUMOVE                       22774
#define ID_BUSCALE                      22775
#define ID_BUSHCAM                      22776
#define ID_BUSNAPGRID                   22777
#define ID_BUREVERSE                    22778
#define ID_BUTSELBRUSH                  22782
#define ID_BUFACESEL                    22783
#define ID_BUVXSEL                      22785
#define ID_BUCYL                        22786
#define ID_BUCONE                       22788
#define ID_BUSTAIRS                     22789
#define ID_BUWIREFRAME                  22791
#define ID_BUSHOWBACK                   22792
#define ID_BUCSG                        22793
#define ID_BUSHOWCSG                    22796
#define ID_BUTINV                       22797
#define ID_MK_BOXHOLLOW                 22798
#define ID_DELETE                       22799
#define ID_CUT                          22800
#define ID_TAB_NEXTSEL                  22801
#define ID_MK_BOX                       22803
#define SB_MOUSECOORD                   22804
#define ID_MK_ROOM                      22805
#define IDS_POLYSCNT                    22806
#define ID_BUSHEET                      22808
#define ID_BURISELOW                    22809
#define MN_PROPS                        22812
#define MN_GLOBALS                      22815
#define MN_ESCAPE                       22816
#define MN_CUT                          22817
#define MN_MIRROR                       22818
#define MN_ENTER                        22819
#define ID_BUALIGN                      22820
#define TBB_XALIGN                      22823
#define TBB_YALIGN                      22824
#define TBB_ZALIGN                      22825
#define TBB_XINTER                      22828
#define TBB_YINTER                      22829
#define TBB_ZINTER                      22830
#define TBB_XDIM                        22831
#define TBB_YDIM                        22832
#define TBB_ZDIM                        22833
#define TBB_XYZDIM                      22834
#define MN_APLLYTEX                     22836
#define MN_TRIANGULATE                  22836
#define IDS_BOXDIM                      22837
#define ID_BUTTON22838                  22838
#define ID_TAB_PREVSEL                  22840
#define ID_SELECTALL                    22841
#define ID_TAB_SELNEXT                  22842
#define ID_TAB_SELPREV                  22843
#define ID_BUCOMPILE                    22846
#define ID_BUVIEWBSP                    22847
#define ID_VIEW_COLORED_LEAFS           22848
#define ID_SELSAMEASSELFACE             22851
#define ID_ALIGH_BOTHIT                 22852
#define ID_ALIGH_TOPHIT                 22853
#define ID_ALIGN_RIGHT_HIT              22854
#define ID_ALIGH_LEFTHIT                22855
#define ID_BUSPHERE                     22856
#define MN_YOY                          22857
#define SB_CAMPOS                       22857
#define MN_XOY                          22857
#define ID_EDIT_MIRROR_XOZ              22858
#define SB_2DPOS                        22858
#define MN_XOZ                          22858
#define ID_EDIT_MIRROR_ZOX              22859
#define SB_BRUSHBBOX                    22859
#define MN_ZOY                          22859
#define SB_MOUSEPOS                     22860
#define MN_SELVERTEX                    22862
#define ID_SETTINGS_PREFERENCES         22874
#define MN_SELECTGROUP                  22876
#define MN_SELCURID                     22877
#define TBB_LR                          22878
#define TBB_TB                          22879
#define TBB_FB                          22880
#define ID_BUTTON22881                  22881
#define TBB_CLOSEDSPLINE                22881
#define ID_MATCHWIDTH                   22886
#define MN_SELITEM                      22887
#define MN_VIEW_LPMAPS                  22888
#define MN_LMTEX                        22890
#define MN_INSITEM                      22891
#define MN_ADD_MODEL                    22893
#define MN_INSPREF                      22894
#define KEY_BSPCURSEL                   22898
#define MN_WPNCFG                       22899
#define IDR_MARGIN_CURSOR               22900
#define IDR_SCREDITOR_ACCEL             22901
#define IDR_L2RSPL                      22901
#define IDR_MARGIN_ICONS                22902
#define IDR_R2LSPL                      22902
#define BMP_3D_TEX                      22903
#define IDR_COMPILING                   22903
#define BMP_CUBE_TEX                    22904
#define SPLASH_EDIT1                    22905
#define E_1                             23008
#define SP_1                            23012
#define S_X                             23013
#define S_Y                             23014
#define S_Z                             23015
#define E_X                             23016
#define E_Y                             23017
#define E_Z                             23018
#define E_U                             23021
#define E_V                             23022
#define S_1                             23025
#define CK_1                            23030
#define CK_2                            23031
#define CK_3                            23032
#define CK_4                            23033
#define CK_5                            23034
#define CK_6                            23035
#define CK_7                            23036
#define CK_8                            23037
#define MN_SCRIPT                       23038
#define MN_SCRIPTBLOCK                  23039
#define MN_COMPILEROPTIONS              23040
#define PB_COMBO                        23042
#define TBB_SELVERTEX                   23043
#define ID_VIEW_SELTOOLBAR              23044
#define ID_VIEW_MOVESIZEROTATETOOBAR    23045
#define ID_VIEW_MOVETOOLBAR             23046
#define ID_VIEW_ALIGNTOOLBAR            23047
#define ID_VIEW_VIEWSTOOLBAR            23048
#define ID_VIEW_CSGTOOLBAR              23049
#define ID_VIEW_BUILDTOOLBAR            23050
#define MN_TEXREFDLG                    23052
#define MN_SHOWSELBBOX                  23055
#define MN_IMP1                         23056
#define MN_IMP2                         23057
#define MN_EXP1                         23058
#define MN_EXP2                         23059
#define ID_FILE_EXPORT_3DS              23060
#define MN_SHOWCOMPILER                 23061
#define ID_SC_NEW                       23062
#define ID_SC_OPEN                      23063
#define ID_SC_SAVE                      23064
#define ID_SC_PRINT                     23065
#define ID_SC_CUT                       23066
#define ID_SC_COPY                      23067
#define ID_SC_PASTE                     23068
#define ID_SC_UNDO                      23069
#define ID_SC_REDO                      23070
#define ID_SC_FIND                      23071
#define ID_SC_REPLACE                   23072
#define ID_SC_REPEAT                    23073
#define ID_SC_FIND_PREVIOUS             23074
#define ID_SC_TOGGLE_BOOKMARK           23075
#define ID_SC_GOTO_NEXT_BOOKMARK        23076
#define ID_SC_GOTO_PREV_BOOKMARK        23077
#define ID_SC_CLEAR_ALL_BOOKMARKS       23078
#define PB_SETTINGS                     23079
#define MN_TERIAN                       23080
#define MN_2DSHAPE                      23081
#define PB_BUILD                        32800
#define PB_SAVE                         32803
#define PB_SAVEAS                       32804
#define ID_SC_SELECT_ALL                36909
#define ID_SC_DELETE                    37000
#define ID_SC_DELETE_BACK               37001
#define ID_SC_DELETE_WORD_BACK          37002
#define ID_SC_TAB                       37003
#define ID_SC_UNTAB                     37004
#define ID_SC_SWITCH_OVRMODE            37005
#define ID_SC_CHAR_LEFT                 37100
#define ID_SC_EXT_CHAR_LEFT             37101
#define ID_SC_CHAR_RIGHT                37102
#define ID_SC_EXT_CHAR_RIGHT            37103
#define ID_SC_WORD_LEFT                 37104
#define ID_SC_EXT_WORD_LEFT             37105
#define ID_SC_WORD_RIGHT                37106
#define ID_SC_EXT_WORD_RIGHT            37107
#define ID_SC_LINE_UP                   37108
#define ID_SC_EXT_LINE_UP               37109
#define ID_SC_LINE_DOWN                 37110
#define ID_SC_EXT_LINE_DOWN             37111
#define ID_SC_SCROLL_UP                 37112
#define ID_SC_SCROLL_DOWN               37113
#define ID_SC_PAGE_UP                   37114
#define ID_SC_EXT_PAGE_UP               37115
#define ID_SC_PAGE_DOWN                 37116
#define ID_SC_EXT_PAGE_DOWN             37117
#define ID_SC_LINE_END                  37118
#define ID_SC_EXT_LINE_END              37119
#define ID_SC_HOME                      37120
#define ID_SC_EXT_HOME                  37121
#define ID_SC_TEXT_BEGIN                37122
#define ID_SC_EXT_TEXT_BEGIN            37123
#define ID_SC_TEXT_END                  37124
#define ID_SC_EXT_TEXT_END              37125
#define ID_SC_TOGGLE_BOOKMARK0          37200
#define ID_SC_TOGGLE_BOOKMARK1          37201
#define ID_SC_TOGGLE_BOOKMARK2          37202
#define ID_SC_TOGGLE_BOOKMARK3          37203
#define ID_SC_TOGGLE_BOOKMARK4          37204
#define ID_SC_TOGGLE_BOOKMARK5          37205
#define ID_SC_TOGGLE_BOOKMARK6          37206
#define ID_SC_TOGGLE_BOOKMARK7          37207
#define ID_SC_TOGGLE_BOOKMARK8          37208
#define ID_SC_TOGGLE_BOOKMARK9          37209
#define ID_SC_GO_BOOKMARK0              37210
#define ID_SC_GO_BOOKMARK1              37211
#define ID_SC_GO_BOOKMARK2              37212
#define ID_SC_GO_BOOKMARK3              37213
#define ID_SC_GO_BOOKMARK4              37214
#define ID_SC_GO_BOOKMARK5              37215
#define ID_SC_GO_BOOKMARK6              37216
#define ID_SC_GO_BOOKMARK7              37217
#define ID_SC_GO_BOOKMARK8              37218
#define ID_SC_GO_BOOKMARK9              37219
#define MN_RECLMAPS                     40001
#define PB_REFR                         40002
#define MN_CONSOLE                      40003
#define MN_SNAPVXES                     40003
#define ID_FILE_MERGE                   40004
#define ID_INSERT                       40005
#define MN_HELP                         40005
#define ID_INSERT_VERTEX                40006
#define MN_CUBEMODEL                    40006
#define MN_INSVX                        40007
#define MN_REMOVEI                      40008
#define MN_EXPP                         40008
#define MN_REMOVEE                      40009
#define MN_PAINTIMER                    40009
#define MN_TERIANBIG                    40010
#define PB_PARSKIN                      40011
#define ID_BUTTON40012                  40012
#define MN_CONEMODEL                    40012
#define ID_BUTTON40013                  40013
#define MN_SPHEREMODEL                  40013
#define ID_BUTTON40014                  40014
#define MN_CYLMODEL                     40014
#define ID_BUTTON40015                  40015
#define MN_SELEDGE                      40015
#define ID_BUTTON40016                  40016
#define MN_REPOINTBRSH                  40016
#define ID_BUTTON40017                  40017
#define MN_IMPP                         40017
#define ID_BUTTON40018                  40018
#define MN_LEAFS                        40018
#define ID_BUTTON40019                  40019
#define MN_DETBRUSHES                   40019
#define ID_BUTTON40020                  40020
#define MN_SELNONDETBRUSHES             40020
#define ID_BUTTON40021                  40021
#define TB_COLOR                        40021
#define ID_BUTTON40022                  40022
#define ID_BUTTON40023                  40023
#define MN_WHITE                        40023
#define ID_BUTTON40024                  40024
#define ID_BUTTON40025                  40025
#define ID_BUTTON40034                  40025
#define ID_BUTTON40026                  40026
#define MN_CLRBYFAR                     40026
#define ID_BUTTON40027                  40027
#define ID_BUTTON40028                  40028
#define ID_BUTTON40029                  40029
#define ID_BUTTON40030                  40030
#define ID_BUTTON40031                  40031
#define ID_BUTTON40032                  40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40035                  40035
#define MN_CUTBYSELBOX                  40036
#define MN_SAMETEXFACE                  40037
#define MN_SAMENORMFACE                 40038
#define MN_INSGAMEITEM                  40039
#define TBB_SPLINE                      40042
#define ID_MIRROR                       -25492
#define MN_EXTRUDE                      40045
#define MN_HALLOUNHALLO                 40046
#define MN_MERGE                        40047
#define MN_PROJ_BRUSH                   40048
#define PB_COMBOTS                      40049
#define MN_PERMCUT                      40050
#define MN_UNDO                         40052
#define MN_TERVOL                       40053
#define MN_MAN_TEX                      40054
#define MN_TO_XML                       40055
#define MN_EXTRACTFACES                 40056
#define MN_EVALDETS                     40058
#define MN_HOME                         40059
#define MN_CREATESB                     40060
#define MN_LOADLASTBACKIP               40061
#define MN_SHOWGRID                     40062
#define MN_WBCK                         40063
#define MN_TRPOLYS                      40064
#define MN_REPOINT                      40065
#define MN_ALBYBOX                      40066
#define TB_ZONES                        40067
#define ID_VIEW_PORTALS                 40068
#define MN_VIEW_FULLCOMP                40069
#define ID_VIEW_LEAF_BY_LEAF            40070
#define ID_VIEW_LIGHTMAPS               40072
#define ID_VIEW_GRAPH                   40073
#define ID_CAM_LSPOT                    40074
#define ID_FILE_SAVESEL_AS              40075
#define MN_INSFACE                      40077
#define MN_CUTWITHBRUSH                 40078
#define MN_TRIFAN                       40079
#define ST_SEP                          40080
#define SB_1                            61449
#define SB_2                            61450
#define SB_3                            61451
#define SB_4                            61452
#define SB_5                            61453
#define SB_6                            61454
#define SB_7                            61455
#define SB_8                            61456
#define SB_9                            61457
#define SB_10                           61458
#define SB_11                           61459
#define SB_12                           61460
#define SB_13                           61461
#define SB_14                           61462
#define SB_15                           61463
#define SB_16                           61464
#define SB_17                           61465
#define SB_EXPL                         61466

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
